Backend: Vivado
ClockPeriod: 5
HLSConfig:
  LayerName:
    cropping2d:
      Precision:
        result: ap_fixed<16,8>
      Trace: false
    flatten:
      Precision:
        result: ap_fixed<16,8>
      Trace: false
    input_1:
      Precision:
        result: ap_fixed<16,8>
      Trace: false
    max_pooling2d:
      Precision:
        result: ap_fixed<16,8>
      Trace: false
    max_pooling2d_1:
      Precision:
        result: ap_fixed<16,8>
      Trace: false
    q_conv2d:
      Precision:
        bias: fixed<4,1>
        result: ap_fixed<16,8>
        weight: fixed<4,1>
      Trace: false
    q_conv2d_1:
      Precision:
        bias: fixed<4,1>
        result: ap_fixed<16,8>
        weight: fixed<4,1>
      Trace: false
    q_conv2d_1_relu:
      Precision:
        result: ap_fixed<16,8>
      Trace: false
    q_conv2d_relu:
      Precision:
        result: ap_fixed<16,8>
      Trace: false
    q_dense:
      Precision:
        bias: fixed<4,1>
        result: ap_fixed<16,8>
        weight: fixed<4,1>
      Trace: false
    q_dense_1:
      Precision:
        bias: fixed<4,1>
        result: ap_fixed<16,8>
        weight: fixed<4,1>
      Trace: false
    q_dense_1_softmax:
      Precision:
        result: ap_fixed<16,8>
      Trace: false
    q_dense_relu:
      Precision:
        result: ap_fixed<16,8>
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision: ap_fixed<16,8>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_stream
InputData: null
KerasModel: !keras_model 'hls4ml_crop_2d_test/keras_model.h5'
OutputDir: hls4ml_crop_2d_test
OutputPredictions: null
Part: xcku035-fbva676-2-e
ProjectName: myproject
Stamp: 0e1a5cfe
Version: 1.0.0
